package app.folga.data

import app.folga.domain.Folga
import app.folga.domain.FolgaRepository
import app.folga.domain.FolgaStatus
import dev.gitlive.firebase.Firebase
import dev.gitlive.firebase.firestore.FirebaseFirestore
import dev.gitlive.firebase.firestore.firestore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import kotlinx.datetime.Clock
import kotlinx.datetime.LocalDate

/**
 * Firestore-backed [FolgaRepository]. All folgas live under the top-level
 * `folgas` collection so queries can filter by `userId` (own folgas) or list
 * everything (trocas picker). Document ids are auto-generated by Firestore.
 */
class FirestoreFolgaRepository(
    private val firestore: FirebaseFirestore = Firebase.firestore,
) : FolgaRepository {

    private val folgas get() = firestore.collection(COLLECTION)

    override suspend fun reserve(userId: String, date: LocalDate, note: String?): Folga {
        val doc = folgas.document
        val folga = Folga(
            id = doc.id,
            userId = userId,
            date = date,
            status = FolgaStatus.SCHEDULED,
            note = note,
            createdAt = Clock.System.now(),
        )
        doc.set(folga.toDto())
        return folga
    }

    override suspend fun cancel(id: String) {
        val ref = folgas.document(id)
        val snapshot = ref.get()
        if (!snapshot.exists) return
        val current = snapshot.data(FolgaDto.serializer())
        ref.set(current.copy(status = FolgaStatus.CANCELLED.name))
    }

    override suspend fun findById(id: String): Folga? {
        val snapshot = folgas.document(id).get()
        if (!snapshot.exists) return null
        return snapshot.data(FolgaDto.serializer()).toDomain()
    }

    override fun observeByUser(userId: String): Flow<List<Folga>> =
        folgas.where { "userId" equalTo userId }.snapshots.map { snap ->
            snap.documents.map { it.data(FolgaDto.serializer()).toDomain() }
        }

    override fun observeAll(): Flow<List<Folga>> =
        folgas.snapshots.map { snap ->
            snap.documents.map { it.data(FolgaDto.serializer()).toDomain() }
        }

    private companion object {
        const val COLLECTION = "folgas"
    }
}
