package app.folga.data

import app.folga.domain.Folga
import app.folga.domain.FolgaRepository
import app.folga.domain.FolgaStatus
import dev.gitlive.firebase.Firebase
import dev.gitlive.firebase.firestore.FirebaseFirestore
import dev.gitlive.firebase.firestore.firestore
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map
import kotlinx.datetime.Clock
import kotlinx.datetime.LocalDate

/**
 * Firestore-backed [FolgaRepository]. All folgas live under the top-level
 * `folgas` collection so queries can filter by `userId` (own folgas) or list
 * everything (trocas picker). Document ids are auto-generated by Firestore.
 */
class FirestoreFolgaRepository(
    private val firestore: FirebaseFirestore = Firebase.firestore,
) : FolgaRepository {

    private val folgas get() = firestore.collection(COLLECTION)

    override suspend fun reserve(userId: String, date: LocalDate, note: String?): Folga {
        val doc = folgas.document
        val folga = Folga(
            id = doc.id,
            userId = userId,
            date = date,
            status = FolgaStatus.SCHEDULED,
            note = note,
            createdAt = Clock.System.now(),
        )
        doc.set(folga.toDto())
        return folga
    }

    override suspend fun cancel(id: String) {
        // Wrap in a transaction with a SCHEDULED guard so cancel never
        // overwrites a status that an already-committed accept() just
        // set to SWAPPED. The symmetrical guard on the swap side
        // (SwapRepository.accept + resolvePending) protects the reverse
        // race; together they guarantee that after a swap is accepted no
        // concurrent cancel can corrupt either folga's state.
        val ref = folgas.document(id)
        firestore.runTransaction {
            val snap = get(ref)
            if (!snap.exists) return@runTransaction
            val current = snap.data(FolgaDto.serializer())
            if (current.status != FolgaStatus.SCHEDULED.name) return@runTransaction
            set(
                documentRef = ref,
                strategy = FolgaDto.serializer(),
                data = current.copy(status = FolgaStatus.CANCELLED.name),
            )
        }
    }

    override suspend fun findById(id: String): Folga? {
        val snapshot = folgas.document(id).get()
        if (!snapshot.exists) return null
        return snapshot.data(FolgaDto.serializer()).toDomain()
    }

    override fun observeByUser(userId: String): Flow<List<Folga>> =
        folgas.where { "userId" equalTo userId }.snapshots.map { snap ->
            snap.documents.map { it.data(FolgaDto.serializer()).toDomain() }
        }.catch { emit(emptyList()) }

    // `catch { emit(emptyList()) }` é defesa contra o crash que aparecia
    // logo depois do logout: o listener do Firestore tava ativo quando
    // `auth.signOut()` derrubava a sessão, então o snapshot seguinte
    // batia em PERMISSION_DENIED (as rules exigem `isSignedIn()`). A
    // exceção subia pelo `combine`/`stateIn` dos ViewModels (que ficam
    // vivos no ViewModelStore da Activity mesmo depois da tela trocar)
    // e caía no uncaughtExceptionHandler do thread main — o app
    // simplesmente fechava sem mensagem nem stack pro usuário.
    // Engolir o erro emitindo lista vazia mantém o app responsivo até
    // o auto-redirect cair pra Login e os ViewModels desinscreverem.
    override fun observeAll(): Flow<List<Folga>> =
        folgas.snapshots.map { snap ->
            snap.documents.map { it.data(FolgaDto.serializer()).toDomain() }
        }.catch { emit(emptyList()) }

    private companion object {
        const val COLLECTION = "folgas"
    }
}
